services:
  - type: web
    name: aasaan-backend
    env: node
    repo: https://github.com/rajathbtu/Aasaan-App.git # Change this to your repo URL
    region: singapore
    plan: free
    rootDir: ./backend
    buildCommand: "npm install && npx prisma migrate deploy && npm run build"
    startCommand: "npx prisma migrate deploy && npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aasaan-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: aasaan-db
    region: singapore
    plan: free
    postgresMajorVersion: 14
