import React, { useState, useCallback, useMemo, useRef, useEffect } from 'react';
import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  Animated,
  RefreshControl,
} from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import * as realApi from '../api';
import { useAuth } from '../contexts/AuthContext';
import { colors, spacing, radius, tints } from '../theme';
import { useI18n } from '../i18n';
import Header from '../components/Header';
import { useNotificationCount } from '../contexts/NotificationCountContext';
import ErrorBanner from '../components/ErrorBanner';
import { offlineCacheKey, readOfflineCache, writeOfflineCache } from '../utils/offlineCache';
import { buildTimeAgo } from '../utils/time';
import SafeBottomBanner from '../components/SafeBottomBanner';
import { getNotificationNavigationTarget } from '../utils/notificationNavigation';

const API = realApi;

/**
 * Displays in‑app notifications generated by the backend.  Users can
 * mark notifications as read individually or all at once.  Each
 * notification shows a type-aware icon, title, message and an
 * approximate timestamp.  Notifications are grouped by day (Today /
 * Yesterday / Earlier) and unread items are visually highlighted.
 */

type TypeStyle = {
  accent: string;
  tint: string;
  icon: keyof typeof Ionicons.glyphMap;
};

/** Visual identity per backend notification type (accent + soft tint + icon). */
const TYPE_STYLES: Record<string, TypeStyle> = {
  newRequest: { accent: colors.primary, tint: tints.blueSoft, icon: 'notifications' },
  requestAccepted: { accent: colors.success, tint: tints.greenSoft, icon: 'checkmark-circle' },
  ratingPrompt: { accent: colors.amber, tint: tints.amberSoft, icon: 'star' },
  boostPromotion: { accent: colors.accent, tint: tints.orangeSoft, icon: 'flash' },
  autoClosed: { accent: colors.grey, tint: colors.surface, icon: 'lock-closed' },
  planPromotion: { accent: colors.violet, tint: tints.purpleSoft, icon: 'trophy' },
};

const DEFAULT_TYPE_STYLE: TypeStyle = {
  accent: colors.primary,
  tint: tints.blueSoft,
  icon: 'information-circle',
};

const getTypeStyle = (type: string): TypeStyle => TYPE_STYLES[type] ?? DEFAULT_TYPE_STYLE;

type ListRow =
  | { kind: 'header'; key: string; title: string; count: number }
  | { kind: 'notification'; key: string; item: any };

/** Pulsing skeleton card shown while the list is loading. */
const SkeletonCard: React.FC = () => {
  const opacity = useRef(new Animated.Value(0.45)).current;
  useEffect(() => {
    const loop = Animated.loop(
      Animated.sequence([
        Animated.timing(opacity, { toValue: 1, duration: 700, useNativeDriver: true }),
        Animated.timing(opacity, { toValue: 0.45, duration: 700, useNativeDriver: true }),
      ])
    );
    loop.start();
    return () => loop.stop();
  }, [opacity]);

  return (
    <Animated.View style={[styles.card, styles.skeletonCard, { opacity }]}>
      <View style={[styles.iconCircle, styles.skeletonBlock]} />
      <View style={styles.cardContent}>
        <View style={[styles.skeletonBlock, { height: 14, width: '55%', marginBottom: spacing.sm }]} />
        <View style={[styles.skeletonBlock, { height: 11, width: '90%', marginBottom: spacing.xs }]} />
        <View style={[styles.skeletonBlock, { height: 11, width: '65%' }]} />
      </View>
    </Animated.View>
  );
};

const NotificationsScreen: React.FC = () => {
  const { token, user } = useAuth();
  const navigation = useNavigation<any>();
  const { t } = useI18n();
  const timeAgo = buildTimeAgo(t);
  const { refresh: refreshUnreadCount } = useNotificationCount();
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [notificationError, setNotificationError] = useState<unknown | null>(null);
  const cacheKey = user?.id ? offlineCacheKey('notifications', user.id) : null;

  const fetchNotifications = async (isRefresh = false) => {
    if (!token || !cacheKey) return;
    try {
      if (isRefresh) setRefreshing(true);
      else setLoading(true);
      const cached = await readOfflineCache<any[]>(cacheKey);
      if (cached && !isRefresh) {
        setNotifications(cached);
        setLoading(false);
      }
      const list = await API.getNotifications(token);
      setNotifications(list);
      await writeOfflineCache(cacheKey, list);
      setNotificationError(null);
      refreshUnreadCount();
    } catch (err) {
      const cached = await readOfflineCache<any[]>(cacheKey);
      if (cached) setNotifications(cached);
      setNotificationError(err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      void fetchNotifications();
      return () => { refreshUnreadCount(); };
    }, [token, cacheKey])
  );

  const unreadCount = useMemo(
    () => notifications.filter((n) => !n.read).length,
    [notifications]
  );

  const markAllRead = async () => {
    if (!token || unreadCount === 0) return;
    try {
      await API.markAllNotificationsRead(token);
      setNotifications((current) => current.map((n) => ({ ...n, read: true })));
      setNotificationError(null);
      refreshUnreadCount();
      fetchNotifications();
    } catch (err) {
      setNotificationError(err);
    }
  };

  const handleNotificationPress = (item: any) => {
    const requestId = item?.data?.requestId || item?.request?.id;
    // Optimistically mark as read so the unread styling clears instantly, then
    // persist to the backend and schedule a low-priority badge refresh.
    if (!item.read && token) {
      setNotifications((current) => current.map((n) => (n.id === item.id ? { ...n, read: true } : n)));
      void API.markNotificationRead(token, item.id)
        .then(() => refreshUnreadCount())
        .catch(() => {});
    }
    if (!user?.role || typeof requestId !== 'string') return;
    const target = getNotificationNavigationTarget(user.role, item.type, requestId);
    if (target) navigation.navigate(target.screen, target.params);
  };

  /** Group notifications into Today / Yesterday / Earlier sections. */
  const rows = useMemo<ListRow[]>(() => {
    const startOfToday = new Date();
    startOfToday.setHours(0, 0, 0, 0);
    const startOfYesterday = new Date(startOfToday);
    startOfYesterday.setDate(startOfYesterday.getDate() - 1);

    const buckets: { key: string; title: string; data: any[] }[] = [
      { key: 'today', title: t('notifications.today'), data: [] },
      { key: 'yesterday', title: t('notifications.yesterday'), data: [] },
      { key: 'earlier', title: t('notifications.earlier'), data: [] },
    ];

    for (const item of notifications) {
      const created = item?.createdAt ? new Date(item.createdAt) : null;
      const time = created?.getTime?.() || 0;
      if (!time || time >= startOfToday.getTime()) buckets[0].data.push(item);
      else if (time >= startOfYesterday.getTime()) buckets[1].data.push(item);
      else buckets[2].data.push(item);
    }

    const result: ListRow[] = [];
    for (const bucket of buckets) {
      if (bucket.data.length === 0) continue;
      result.push({ kind: 'header', key: bucket.key, title: bucket.title, count: bucket.data.length });
      for (const item of bucket.data) {
        result.push({ kind: 'notification', key: item.id, item });
      }
    }
    return result;
  }, [notifications, t]);

  const hasAction = (item: any) => {
    const requestId = item?.data?.requestId || item?.request?.id;
    if (!user?.role || typeof requestId !== 'string') return false;
    return getNotificationNavigationTarget(user.role, item.type, requestId) !== null;
  };


  const renderNotificationRow = (item: any) => {
    const { accent, tint, icon } = getTypeStyle(item.type || '');
    const unread = !item.read;
    return (
      <TouchableOpacity
        activeOpacity={0.85}
        onPress={() => handleNotificationPress(item)}
        style={[styles.card, unread ? styles.cardUnread : styles.cardRead]}
      >
        <View style={[styles.iconCircle, { backgroundColor: tint }]}>
          <Ionicons name={icon} size={22} color={accent} />
          {unread && <View style={[styles.iconDot, { backgroundColor: accent }]} />}
        </View>
        <View style={styles.cardContent}>
          <View style={styles.titleRow}>
            <Text style={[styles.cardTitle, unread && styles.cardTitleUnread]} numberOfLines={1}>
              {item.title}
            </Text>
            <Text style={styles.cardTime}>{timeAgo(item.createdAt)}</Text>
          </View>
          <Text style={styles.cardMessage} numberOfLines={2}>{item.message}</Text>
          <View style={styles.metaRow}>
            {unread && (
              <View style={[styles.newPill, { backgroundColor: tint }]}>
                <Text style={[styles.newPillText, { color: accent }]}>{t('notifications.newBadge')}</Text>
              </View>
            )}
            {hasAction(item) && (
              <View style={styles.chevronRow}>
                <Text style={styles.chevronText}>{t('notifications.viewDetails')}</Text>
                <Ionicons name="chevron-forward" size={14} color={accent} />
              </View>
            )}
          </View>
        </View>
      </TouchableOpacity>
    );
  };

  const renderItem = ({ item }: { item: ListRow }) => {
    if (item.kind === 'header') {
      return (
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionHeaderText}>{item.title}</Text>
          <View style={styles.sectionCount}>
            <Text style={styles.sectionCountText}>{item.count}</Text>
          </View>
        </View>
      );
    }
    return renderNotificationRow(item.item);
  };


  if (loading) {
    return (
      <View style={styles.container}>
        <Header
          title={t('notifications.title')}
          showBackButton={true}
          showNotification={false}
        />
        <View style={styles.skeletonWrap}>
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* Header */}
      <Header
        title={t('notifications.title')}
        showBackButton={true}
        showNotification={false}
        customRightComponent={
          <TouchableOpacity
            onPress={markAllRead}
            disabled={unreadCount === 0}
            style={[styles.markAllButton, unreadCount === 0 && styles.markAllButtonDisabled]}
            accessibilityRole="button"
            accessibilityLabel={t('notifications.markAllRead')}
          >
            <Ionicons
              name="checkmark-done"
              size={16}
              color={unreadCount === 0 ? colors.greyMuted : colors.primary}
            />
            <Text style={[styles.markAllText, unreadCount === 0 && styles.markAllTextDisabled]}>
              {t('notifications.markAllRead')}
            </Text>
            {unreadCount > 0 && (
              <View style={styles.markAllBadge}>
                <Text style={styles.markAllBadgeText}>{unreadCount}</Text>
              </View>
            )}
          </TouchableOpacity>
        }
      />
      {/* Small spacer to prevent overlap and keep consistent spacing below header */}
      <View style={{ height: spacing.sm }} />
      <FlatList
        data={rows}
        keyExtractor={(row) => row.key}
        renderItem={renderItem}
        ListEmptyComponent={
          <View style={styles.emptyContainer}>
            <View style={styles.emptyIconCircle}>
              <Ionicons name="notifications-off-outline" size={40} color={colors.primary} />
            </View>
            <Text style={styles.emptyTitle}>{t('notifications.emptyTitle')}</Text>
            <Text style={styles.emptySubtitle}>{t('notifications.emptySubtitle')}</Text>
          </View>
        }
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => fetchNotifications(true)}
            tintColor={colors.primary}
            colors={[colors.primary]}
          />
        }
        contentContainerStyle={{ paddingBottom: spacing.xl + 80 }}
        showsVerticalScrollIndicator={false}
      />
      <ErrorBanner error={notificationError} onRetry={fetchNotifications} />
      <SafeBottomBanner/>
    </View>
  );
};


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.light,
  },
  /* Header mark-all-read pill */
  markAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: colors.primaryLight,
    gap: spacing.xs,
  },
  markAllButtonDisabled: {
    backgroundColor: colors.surface,
  },
  markAllText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  markAllTextDisabled: {
    color: colors.greyMuted,
  },
  markAllBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: 10,
    backgroundColor: colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markAllBadgeText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  /* Section headers */
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  sectionHeaderText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.grey,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sectionCount: {
    marginLeft: spacing.sm,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.grey,
  },
  /* Cards */
  card: {
    flexDirection: 'row',
    padding: spacing.mdPlus,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    borderRadius: radius.xl,
    alignItems: 'flex-start',
  },
  cardRead: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.greyLight,
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardUnread: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    shadowColor: colors.primary,
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  iconDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 11,
    height: 11,
    borderRadius: 5.5,
    borderWidth: 2,
    borderColor: colors.white,
  },

  cardContent: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
    gap: spacing.sm,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.dark,
    flexShrink: 1,
  },
  cardTitleUnread: {
    fontWeight: '800',
  },
  cardTime: {
    fontSize: 11,
    color: colors.greyMuted,
  },
  cardMessage: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.grey,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  newPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: radius.sm,
  },
  newPillText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  chevronRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  chevronText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.grey,
  },
  /* Skeletons */
  skeletonWrap: {
    flex: 1,
    paddingTop: spacing.sm,
  },
  skeletonCard: {
    elevation: 0,
    shadowOpacity: 0,
    borderWidth: 0,
  },
  skeletonBlock: {
    backgroundColor: colors.greyLight,
    borderRadius: radius.sm,
  },
  /* Empty state */
  emptyContainer: {
    alignItems: 'center',
    paddingTop: spacing.xxl + spacing.xl,
    paddingHorizontal: spacing.xl,
  },
  emptyIconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.dark,
    marginBottom: spacing.xs,
  },
  emptySubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.grey,
    textAlign: 'center',
    maxWidth: 280,
  },
});

export default NotificationsScreen;
